//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_hoa_don_doi_tra
    {
        public int ma_hoa_don { get; set; }
        public int ma_thuoc_tinh { get; set; }
        public string trang_thai { get; set; }
        public int so_luong { get; set; }
        public decimal gia { get; set; }
        public decimal giagiam { get; set; }
        public Nullable<decimal> thanh_tien { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual hoa_don_doi_tra hoa_don_doi_tra { get; set; }
        public virtual thuoc_tinh_san_pham thuoc_tinh_san_pham { get; set; }
    }
}
