//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_nhap_hang
    {
        public int ma_nhap_hang { get; set; }
        public int ma_san_pham { get; set; }
        public int so_luong { get; set; }
        public decimal gia_nhap { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual nhap_hang nhap_hang { get; set; }
        public virtual san_pham san_pham { get; set; }
    }
}
