//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_don_web
    {
        public int id_don_hang { get; set; }
        public int ma_thuoc_tinh { get; set; }
        public int so_luong { get; set; }
        public decimal gia { get; set; }
        public Nullable<decimal> thanh_tien { get; set; }
    
        public virtual don_dat_hang_web don_dat_hang_web { get; set; }
        public virtual thuoc_tinh_san_pham thuoc_tinh_san_pham { get; set; }
    }
}
