//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_SHOP_FASHIONEntities5 : DbContext
    {
        public QL_SHOP_FASHIONEntities5()
            : base("name=QL_SHOP_FASHIONEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chi_tiet_don_web> chi_tiet_don_web { get; set; }
        public virtual DbSet<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        public virtual DbSet<chi_tiet_hoa_don_doi_tra> chi_tiet_hoa_don_doi_tra { get; set; }
        public virtual DbSet<chi_tiet_nhap_hang> chi_tiet_nhap_hang { get; set; }
        public virtual DbSet<don_dat_hang_web> don_dat_hang_web { get; set; }
        public virtual DbSet<hinh_anh_san_pham> hinh_anh_san_pham { get; set; }
        public virtual DbSet<hoa_don> hoa_don { get; set; }
        public virtual DbSet<hoa_don_doi_tra> hoa_don_doi_tra { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<khuyen_mai> khuyen_mai { get; set; }
        public virtual DbSet<kich_thuoc> kich_thuoc { get; set; }
        public virtual DbSet<loai_san_pham> loai_san_pham { get; set; }
        public virtual DbSet<man_hinh> man_hinh { get; set; }
        public virtual DbSet<mau_sac> mau_sac { get; set; }
        public virtual DbSet<nha_cung_cap> nha_cung_cap { get; set; }
        public virtual DbSet<nha_cung_cap_san_pham> nha_cung_cap_san_pham { get; set; }
        public virtual DbSet<nhan_vien> nhan_vien { get; set; }
        public virtual DbSet<nhap_hang> nhap_hang { get; set; }
        public virtual DbSet<nhom_loai> nhom_loai { get; set; }
        public virtual DbSet<nhom_quyen> nhom_quyen { get; set; }
        public virtual DbSet<phan_quyen> phan_quyen { get; set; }
        public virtual DbSet<phuong_thuc_thanh_toan> phuong_thuc_thanh_toan { get; set; }
        public virtual DbSet<san_pham> san_pham { get; set; }
        public virtual DbSet<tai_khoan> tai_khoan { get; set; }
        public virtual DbSet<tai_khoan_nhom_quyen> tai_khoan_nhom_quyen { get; set; }
        public virtual DbSet<thong_tin_san_pham> thong_tin_san_pham { get; set; }
        public virtual DbSet<thuoc_tinh_san_pham> thuoc_tinh_san_pham { get; set; }
        public virtual DbSet<thuong_hieu> thuong_hieu { get; set; }
    }
}
