//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don_doi_tra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoa_don_doi_tra()
        {
            this.chi_tiet_hoa_don_doi_tra = new HashSet<chi_tiet_hoa_don_doi_tra>();
        }
    
        public int ma_hoa_don { get; set; }
        public Nullable<int> ma_nhan_vien { get; set; }
        public Nullable<int> ma_phuong_thuc { get; set; }
        public Nullable<int> tong_so_luong { get; set; }
        public Nullable<System.DateTime> ngay_doi_tra { get; set; }
        public Nullable<decimal> tien_doi_diem { get; set; }
        public Nullable<decimal> tien_hang_tra { get; set; }
        public Nullable<decimal> tien_mua_them { get; set; }
        public Nullable<decimal> tien_hoan { get; set; }
        public Nullable<decimal> tien_khach_tra { get; set; }
        public Nullable<decimal> tong_tien_sau_khi_doi { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_hoa_don_doi_tra> chi_tiet_hoa_don_doi_tra { get; set; }
        public virtual hoa_don hoa_don { get; set; }
        public virtual nhan_vien nhan_vien { get; set; }
        public virtual phuong_thuc_thanh_toan phuong_thuc_thanh_toan { get; set; }
    }
}
