//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoa_don
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoa_don()
        {
            this.chi_tiet_hoa_don = new HashSet<chi_tiet_hoa_don>();
        }
    
        public int ma_hoa_don { get; set; }
        public Nullable<int> ma_khach_hang { get; set; }
        public Nullable<int> ma_nhan_vien { get; set; }
        public Nullable<System.DateTime> ngay_lap { get; set; }
        public Nullable<int> ma_khuyen_mai { get; set; }
        public string trang_thai_giao_hang { get; set; }
        public Nullable<int> ma_phuong_thuc { get; set; }
        public Nullable<int> tong_so_luong_mua { get; set; }
        public Nullable<decimal> tien_giam { get; set; }
        public Nullable<decimal> tong_tien { get; set; }
        public Nullable<decimal> tien_doi_diem { get; set; }
        public Nullable<bool> doi_diem { get; set; }
        public Nullable<decimal> tong_gia_tri { get; set; }
        public decimal tong_don_hang { get; set; }
        public bool hinh_thuc_ban { get; set; }
        public int trang_thai_doi_tra { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        public virtual khach_hang khach_hang { get; set; }
        public virtual khuyen_mai khuyen_mai { get; set; }
        public virtual nhan_vien nhan_vien { get; set; }
        public virtual phuong_thuc_thanh_toan phuong_thuc_thanh_toan { get; set; }
        public virtual hoa_don_doi_tra hoa_don_doi_tra { get; set; }
    }
}
