//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class khach_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khach_hang()
        {
            this.hoa_don = new HashSet<hoa_don>();
        }
    
        public int ma_khach_hang { get; set; }
        public string ten_khach_hang { get; set; }
        public string dien_thoai { get; set; }
        public string dia_chi { get; set; }
        public Nullable<int> diem_thuong { get; set; }
        public Nullable<int> diem_da_doi { get; set; }
        public Nullable<int> tai_khoan_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don> hoa_don { get; set; }
        public virtual tai_khoan tai_khoan { get; set; }
    }
}
