//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class khuyen_mai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khuyen_mai()
        {
            this.hoa_don = new HashSet<hoa_don>();
        }
    
        public int ma_khuyen_mai { get; set; }
        public string code { get; set; }
        public decimal gia_tri { get; set; }
        public Nullable<System.DateTime> thoi_gian_bat_dau { get; set; }
        public Nullable<System.DateTime> thoi_gian_ket_thuc { get; set; }
        public Nullable<int> so_luong_toi_da { get; set; }
        public Nullable<int> so_luong_da_dung { get; set; }
        public string tinh_trang { get; set; }
        public string ghi_chu { get; set; }
        public decimal gia_tri_hoa_don_toi_thieu { get; set; }
        public Nullable<int> ma_nhan_vien { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoa_don> hoa_don { get; set; }
        public virtual nhan_vien nhan_vien { get; set; }
    }
}
