//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhap_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhap_hang()
        {
            this.chi_tiet_nhap_hang = new HashSet<chi_tiet_nhap_hang>();
        }
    
        public int ma_nhap_hang { get; set; }
        public Nullable<int> ma_nhan_vien { get; set; }
        public Nullable<int> ma_nha_cung_cap { get; set; }
        public Nullable<System.DateTime> ngay_nhap { get; set; }
        public string trang_thai { get; set; }
        public string ghi_chu { get; set; }
        public int tong_so_luong { get; set; }
        public decimal tong_gia_tien { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_nhap_hang> chi_tiet_nhap_hang { get; set; }
        public virtual nha_cung_cap nha_cung_cap { get; set; }
        public virtual nhan_vien nhan_vien { get; set; }
    }
}
