//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class phan_quyen
    {
        public int id_man_hinh { get; set; }
        public int id_nhom_quyen { get; set; }
        public Nullable<bool> co_quyen { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    
        public virtual man_hinh man_hinh { get; set; }
        public virtual nhom_quyen nhom_quyen { get; set; }
    }
}
