//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tai_khoan_nhom_quyen
    {
        public int tai_khoan_id { get; set; }
        public int id_nhom_quyen { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    
        public virtual nhom_quyen nhom_quyen { get; set; }
        public virtual tai_khoan tai_khoan { get; set; }
    }
}
