//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tai_khoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tai_khoan()
        {
            this.khach_hang = new HashSet<khach_hang>();
            this.nhan_vien = new HashSet<nhan_vien>();
            this.tai_khoan_nhom_quyen = new HashSet<tai_khoan_nhom_quyen>();
        }
    
        public int tai_khoan_id { get; set; }
        public string ten_dang_nhap { get; set; }
        public string mat_khau_hash { get; set; }
        public Nullable<bool> hoat_dong { get; set; }
        public Nullable<bool> is_oauth { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<khach_hang> khach_hang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nhan_vien> nhan_vien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tai_khoan_nhom_quyen> tai_khoan_nhom_quyen { get; set; }
    }
}
