//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSHOPFASHION.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class thuoc_tinh_san_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public thuoc_tinh_san_pham()
        {
            this.chi_tiet_don_web = new HashSet<chi_tiet_don_web>();
            this.chi_tiet_hoa_don = new HashSet<chi_tiet_hoa_don>();
            this.chi_tiet_hoa_don_doi_tra = new HashSet<chi_tiet_hoa_don_doi_tra>();
        }
    
        public int ma_thuoc_tinh { get; set; }
        public Nullable<int> ma_san_pham { get; set; }
        public Nullable<int> ma_kich_thuoc { get; set; }
        public Nullable<int> ma_mau_sac { get; set; }
        public Nullable<int> so_luong_ton { get; set; }
        public Nullable<decimal> gia_ban { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_web> chi_tiet_don_web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_hoa_don> chi_tiet_hoa_don { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_hoa_don_doi_tra> chi_tiet_hoa_don_doi_tra { get; set; }
        public virtual kich_thuoc kich_thuoc { get; set; }
        public virtual mau_sac mau_sac { get; set; }
        public virtual san_pham san_pham { get; set; }
    }
}
